Ochampari/unify add score dialogs
Caleydo/tdp_publicdb pull request #124
Opened 2020-10-08 07:17 UTC by oltionchampari

Coming from Caleydo/tdp_bi_bioinfodb#1143

### Summary 
* Refactored the `cell line | gene | tissue` annotation scores to support multiple selection 

#### before 
---
![an_col_before](https://user-images.githubusercontent.com/51322092/95426318-fb649b00-0945-11eb-89e1-298d3ddfdd3b.png)

#### after 
---
![ann_col_after](https://user-images.githubusercontent.com/51322092/95426345-07505d00-0946-11eb-8b94-f15cd30b4148.png)

* Changed the button text to `Add`  for all score dialogs (i could not find any mention in any PRs that the button texts were explicitly defined)

#### before
---
![adc_before](https://user-images.githubusercontent.com/51322092/95426510-4f6f7f80-0946-11eb-8fc8-d2e20db9b970.png)
![agc_before](https://user-images.githubusercontent.com/51322092/95426512-4f6f7f80-0946-11eb-98ca-e48f8aad4375.png)
![sc_before](https://user-images.githubusercontent.com/51322092/95426513-50081600-0946-11eb-89e2-991b85363202.png)

#### after
---
![button_after](https://user-images.githubusercontent.com/51322092/95426543-5bf3d800-0946-11eb-91bb-f231d0e92baa.png)

* Added a new i18next namespace. The rest of the strings we can extract in another issue
* Fixed the tours to work with the new dialogs and button names

2020-10-08 07:23 UTC, oltionchampari commented on src/phovea.ts
> +export default function (registry) {
This is  **.ts** file we should use ES6 Modules

2020-10-12 12:05 UTC, thinkh requested changes
Thanks for your changes. In general your changes work for me. However, I found some problems with existing sessions. Please fix the remaining bugs.

Special thanks that you remembered to adapt the tour accordingly. 👍

2020-10-12 12:05 UTC, thinkh commented on src/scores/AnnotationColumn.ts
> +    return data.map((d) => new AnnotationColumn(d, primary));
This does not work with existing provenance graphs and causes errors!

![grafik](https://user-images.githubusercontent.com/5851088/95744449-984f6d00-0c93-11eb-88ea-f69bcfdc1545.png)

Please check if `data` is an array and handle both cases (single data and data array).

2020-10-13 12:50 UTC, oltionchampari commented on src/scores/GeneSignatureScore.ts
> +    return data.map(({params, options}) => new GeneSignatureScore(params, primary, options));
@thinkh Thanks for thinking of this. Implemented the requested changes.

2020-10-14 07:42 UTC, thinkh approved these changes
Thanks for your fixes. It works now as expected. 👍

2020-10-14 07:43 UTC, merged