Reload named sets when modified
Caleydo/tdp_publicdb pull request #185
Opened 2022-05-04 09:14 UTC by oltionchampari

Closes https://github.com/Caleydo/tdp_bi_bioinfodb/issues/1359

### Summary
* Added listener to listen when a ranking saves a named set
* Pass the onEdit and onDelete callbacks to the named set to relaod the named sets instead of modifing them locally

2022-05-04 09:22 UTC, oltionchampari commented
Build fails because of the required branch in ordino

2022-05-05 09:01 UTC, thinkh requested changes
Thanks for your changes. Please have take a look at the `dirty` flag handling. It looks weird to me and should be fixed. After the change please test again if the updating still works correctly. I could also imagine that setting the dirty flag to `true` triggers a new HTTP request to fetch the named sets and triggers the whole loading and update cycle of the list.

2022-05-06 10:03 UTC, oltionchampari commented on src/menu/DatasetCard.tsx
>      // eslint-disable-next-line react-hooks/exhaustive-deps
Simplified the logic here a bit, as a consequence of properly implementing the `dirtyNamedSets` logic.

2022-05-06 10:03 UTC, oltionchampari commented on src/menu/DatasetCard.tsx
> +      setDirtyNamedSets((d) => !d);
Thanks for the suggestion

2022-05-06 10:05 UTC, oltionchampari commented on src/menu/DatasetCard.tsx
> +  }, [dataSource.idType]);
Was trying to shut up the linter, and it would have had any sideffects as far as i understand since the idType would never change. Removed it though.

2022-05-06 10:05 UTC, oltionchampari commented on src/menu/DatasetCard.tsx
> +import React, { useEffect } from 'react';
Done

2022-05-06 11:30 UTC, thinkh commented on src/menu/DatasetCard.tsx
> +    setDirtyNamedSets(false);
I would leave it like it is now.

2022-05-06 11:31 UTC, thinkh approved these changes
Thanks for your refactoring. It looks good to me now. I also tested the named set list again and it works for me as expected.

2022-05-06 11:31 UTC, thinkh commented on src/menu/DatasetCard.tsx
>      // eslint-disable-next-line react-hooks/exhaustive-deps
Thanks! 👍

2022-05-06 11:34 UTC, merged